version: "3.9"

services:
  db:
    image: postgres:15
    container_name: book-shop-db-${DEPLOY_ENV}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_${DEPLOY_ENV}:/var/lib/postgresql/data
    networks:
      - book-shop-network-${DEPLOY_ENV}
    restart: always

  backend:
    image: ${DOCKER_IMAGE}
    container_name: book-shop-backend-${DEPLOY_ENV}
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      DB_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    depends_on:
      - db
    networks:
      - book-shop-network-${DEPLOY_ENV}
    restart: always

  nginx:
    image: nginx:alpine
    container_name: book-shop-nginx-${DEPLOY_ENV}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
    networks:
      - book-shop-network-${DEPLOY_ENV}
    restart: always

volumes:
  postgres_data_${DEPLOY_ENV}:

networks:
  book-shop-network-${DEPLOY_ENV}:
    driver: bridge
